
def options(opt):
    opt.load('compiler_d')

def configure(cnf):
    cnf.load('compiler_d')

def build(bld):
    addProgram(bld, 'grid', 'grid/main.d')

def addProgram(bld, module, additionalSources=''):
    title = module.title( )
    bld.program(source=module + '/' + title + '.d ' + additionalSources,
                target=title, dflags='-I.. -I/usr/local/include/d -g',
                libpath='/usr/local/lib/libgtkd.a', lib='dl')
